format = """\
[╭─](fg:arrow)\
$directory[](fg:red)\
(\
    $git_branch\
    $git_status\
)
[╰──](fg:arrow)$character\
"""
# Add the modules you need

# Disables the blank line at the start of the prompt
# add_newline = true

continuation_prompt = '   [▶](bold green) '
palette = "mocha"

[palettes.mocha]
black = "#1e1e2e" #Yes, black == base
white = "#cdd6f4"
red = "#e78284"
blue = "#8caaee"
mauve = "#ca9ee6"
green = "#a6d189"
base = "#1e1e2d"
crust = "#11111b"
mantle = "#181825"
trans = "#1e1e2e"

[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"

[directory]
format = "[](fg:red bg:trans)[](fg:base bg:red)[ $path ]($style bold)[](fg:base bg:red)[$read_only]($read_only_style bold)"
truncation_length = 6
style = "fg:red bg:base"
read_only_style = "fg:base bg:red"
before_repo_root_style = "fg:red bg:base"
truncation_symbol = "../"
truncate_to_repo = true
read_only ="  "

[git_branch]
format = "─[](fg:mauve)[](fg:base bg:mauve)[ $symbol$branch ](fg:mauve bg:base bold)[](fg:base bg:mauve)"
symbol = " "

[git_status]
format = '([ $all_status$ahead_behind ]($style bold)[](fg:mauve))'
style = "fg:base bg:mauve"

[docker_context]
disabled=true
symbol = " "
