format = """\
[╭─](fg:arrow)\
$directory\
(\
    $git_branch\
    $git_status\
)
[╰─](fg:arrow)$character\
"""
# Add the modules you need

# Disables the blank line at the start of the prompt
add_newline = true

continuation_prompt = '  ▶ '
# Palettes:
#   old: the previous version.
#   normal: dark gray / yellow / white palette.
#   light: pastel light colors.
# To change the colors: change to the corresponding palette.
palette = "light"

[palettes.light]
arrow = "#cdd6f4"
os = "#a6e3a1"
os_admin = "#a6e3a1"
directory = "#cba6f7"
time = "#89dceb"
git = "#b4befe"
git_status = "#94e2d5"
text_color = "#1e1e2e"
text_light = "#1e1e2e"

[username]
style_user = 'os'
style_root = 'os_admin'
format = '[]($style)[   Rice ](bg:$style fg:text_color)[]($style)'
disabled = false
show_always = true

[character]
success_symbol = "[](fg:arrow)"
error_symbol = "[](fg:red)"

[directory]
format = "[](fg:directory)[  $path]($style)[$read_only]($read_only_style)[](fg:directory)"
truncation_length = 30
style = "fg:text_color bg:directory"
read_only_style = "fg:text_color bg:directory"
before_repo_root_style = "fg:text_color bg:directory"
truncation_symbol = " /"
truncate_to_repo = true
read_only ="  "

[git_branch]
format = "─[](fg:git)[$symbol$branch ](fg:text_light bg:git)[](fg:git)"
symbol = " "

[git_status]
format = '([](fg:git_status)[ $all_status$ahead_behind]($style)[](fg:git_status))'
style = "fg:text_light bg:git_status"

[docker_context]
disabled=true
symbol = " "
